name: CI
permissions:
  contents: read

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
      - name: Install npm deps
        run: npm install
      - name: Run linter
        run: npm run lint
      - name: Run tests with coverage
        run: npm run pretest && npm run instrument && xvfb-run -a node ./out/test/runTest.js
      - name: Generate coverage report
        run: npm run coverage:report
      - name: Check coverage threshold
        run: npm run coverage:check
